# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Ruby environment (required for Jekyll)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Choose your preferred Ruby version, recommended: 2.7

      # Install dependencies (Jekyll, Bundler, etc.)
      - name: Install dependencies
        working-directory: site
        run: |
          gem install bundler -v 2.4.22
          bundle _2.4.22_ install 

      # Build the Jekyll site
      - name: Build the site
        working-directory: site
        run: |
           bundle _2.4.22_ exec jekyll build

      # Deploy to GitHub Pages (typically the gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.1
        with:
          branch: gh-pages  # The branch that GitHub Pages uses
          folder: site/_site   # The folder where Jekyll generates the site

